version: "3.9"
services:
  bot:
    image: kjelenak/discord-fast:latest
    build: .
    volumes:
      - .:/discord
    ports:
      - "8443:8443"
    command: uvicorn run_bot:app --reload --port 8443 --host 0.0.0.0